# config/packages/framework.yaml
framework:
    secret: '%env(APP_SECRET)%'

    # Session configuration
    session:
        enabled: true
        cookie_lifetime: 604800   # Session cookie expires after 10 seconds
        gc_maxlifetime: 604800    # Session data expires after 10 seconds
        name: 'app_session'
        cookie_path: '/'
        cookie_domain: '127.0.0.1'
        cookie_secure: false
        cookie_httponly: true
        cookie_samesite: 'lax'

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            handler_id: null  # Default Symfony session handler
            cookie_lifetime: 604800    # Adjust as needed (usually in seconds)
            gc_maxlifetime: 604800     # Session expiration on server