security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    
    providers:
        members_provider:
            entity:
                class: App\Entity\Members
                property: email
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
    
        main:
            lazy: true
            provider: members_provider
            form_login:
                login_path: app_login
                check_path: login_check
                enable_csrf: true
                username_parameter: '_username'
                password_parameter: '_password'
            logout:
                path: app_logout
                target: app_login
    
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER  # Admins automatically get USER privileges
    
    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/user, roles: ROLE_USER }