security:
    # Password hashers configuration (keeps the default settings)
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # User provider configuration
    providers:
        members_provider:
            entity:
                class: App\Entity\Members
                property: email  # or whatever the unique field is (e.g., username or email)

    firewalls:
        # Developer specific firewall rules
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Main firewall configuration
        main:
            lazy: true
            provider: members_provider  # Use the members_provider for user authentication

            # Enable form login (or any other authentication methods you wish)
            form_login:
                login_path: app_login
                check_path: app_login
            logout:
                path: app_logout
                target: app_login  # Redirect to login page after logout

    # Access control settings
    access_control:
        # Example access control: only admins can access the admin section
        - { path: ^/admin, roles: ROLE_ADMIN }
        # Regular users can access their own profile
        - { path: ^/profile, roles: ROLE_USER }
